const barks = [

    {
        img: "images/dog7.png",
        highlight: "images/dog7-highlight.png",
        name: "weary town",
        file: "bark-01.wav",
    },
    {
        img: "images/dog5.png",
        highlight: "images/dog5-highlight.png",
        name: "posh remove",
        file: "bark-02.wav",
    },
    {
        img: "images/dog4.png",
        highlight: "images/dog4-highlight.png",
        name: "grandiose matter",
        file: "bark-03.wav",
    },
    {
        img: "images/dog5.png",
        highlight: "images/dog5-highlight.png",
        name: "welcome month",
        file: "bark-04.wav",
    },
    {
        img: "images/dog3.png",
        highlight: "images/dog3-highlight.png",
        name: "nautical front",
        file: "bark-05.wav",
    },
    {
        img: "images/dog3.png",
        highlight: "images/dog3-highlight.png",
        name: "live post",
        file: "bark-06.wav",
    },
    {
        img: "images/dog5.png",
        highlight: "images/dog5-highlight.png",
        name: "unpleasant safety",
        file: "bark-07.wav",
    },
    {
        img: "images/dog7.png",
        highlight: "images/dog7-highlight.png",
        name: "robust code",
        file: "bark-08.wav",
    },
    {
        img: "images/dog1.png",
        highlight: "images/dog1-highlight.png",
        name: "downright punch",
        file: "bark-09.wav",
    },
    {
        img: "images/dog2.png",
        highlight: "images/dog2-highlight.png",
        name: "imperfect salt",
        file: "bark-10.wav",
    },
    {
        img: "images/dog1.png",
        highlight: "images/dog1-highlight.png",
        name: "splendid safety",
        file: "bark-11.wav",
    },
    {
        img: "images/dog5.png",
        highlight: "images/dog5-highlight.png",
        name: "tidy funeral",
        file: "bark-12.wav",
    },
    {
        img: "images/dog2.png",
        highlight: "images/dog2-highlight.png",
        name: "warm ring",
        file: "bark-13.wav",
    },
    {
        img: "images/dog6.png",
        highlight: "images/dog6-highlight.png",
        name: "quick national",
        file: "bark-14.wav",
    },
    {
        img: "images/dog7.png",
        highlight: "images/dog7-highlight.png",
        name: "velvety bag",
        file: "bark-15.wav",
    },
    {
        img: "images/dog3.png",
        highlight: "images/dog3-highlight.png",
        name: "paltry count",
        file: "bark-16.wav",
    },
    {
        img: "images/dog5.png",
        highlight: "images/dog5-highlight.png",
        name: "productive role",
        file: "bark-17.wav",
    },
    {
        img: "images/dog5.png",
        highlight: "images/dog5-highlight.png",
        name: "bright tree",
        file: "bark-18.wav",
    },
    {
        img: "images/dog7.png",
        highlight: "images/dog7-highlight.png",
        name: "green knowledge",
        file: "bark-19.wav",
    },
    {
        img: "images/dog5.png",
        highlight: "images/dog5-highlight.png",
        name: "tan draft",
        file: "bark-20.wav",
    },
    {
        img: "images/dog2.png",
        highlight: "images/dog2-highlight.png",
        name: "gummy section",
        file: "bark-21.wav",
    },
    {
        img: "images/dog2.png",
        highlight: "images/dog2-highlight.png",
        name: "creamy officer",
        file: "bark-22.wav",
    },
    {
        img: "images/dog7.png",
        highlight: "images/dog7-highlight.png",
        name: "alert year",
        file: "bark-23.wav",
    },
    {
        img: "images/dog2.png",
        highlight: "images/dog2-highlight.png",
        name: "giving put",
        file: "bark-24.wav",
    },
    {
        img: "images/dog4.png",
        highlight: "images/dog4-highlight.png",
        name: "boiling resolution",
        file: "bark-25.wav",
    },];
