const barks = [
  ["weary town", "bark-01.wav"],
  ["posh remove", "bark-02.wav"],
  ["grandiose matter", "bark-03.wav"],
  ["welcome month", "bark-04.wav"],
  ["nautical front", "bark-05.wav"],
  ["live post", "bark-06.wav"],
  ["unpleasant safety", "bark-07.wav"],
  ["robust code", "bark-08.wav"],
  ["downright punch", "bark-09.wav"],
  ["imperfect salt", "bark-10.wav"],
  ["splendid safety", "bark-11.wav"],
  ["tidy funeral", "bark-12.wav"],
  ["warm ring", "bark-13.wav"],
  ["quick national", "bark-14.wav"],
  ["velvety bag", "bark-15.wav"],
  ["paltry count", "bark-16.wav"],
  ["productive role", "bark-17.wav"],
  ["bright tree", "bark-18.wav"],
  ["green knowledge", "bark-19.wav"],
  ["tan draft", "bark-20.wav"],
  ["gummy section", "bark-21.wav"],
  ["creamy officer", "bark-22.wav"],
  ["alert year", "bark-23.wav"],
  ["giving put", "bark-24.wav"],
  ["boiling resolution", "bark-25.wav"],
];
